"use client";

import { FormEvent, useState } from "react";
import { restoreBuilderSubmission } from "../../../lib/game/draft";
import EvaluationResults, { type Criterion, type Evaluation } from "./evaluation-results";
import { useReportLevelDraft, useReportLevelPhase } from "./level-phase";

type Field = { id: string; label: string; prompt: string; placeholder?: string; maxChars: number };
type BuilderResponse = { evaluation?: Evaluation | "pending"; awardedXp?: number; isReplay?: boolean };

export default function BuilderClient({ slug, title, instructions, fields, rubric, nextSlug, initialSubmission }: { slug: string; title: string; instructions: string; fields: Field[]; rubric: Criterion[]; nextSlug?: string; initialSubmission?: Record<string, string> }) {
  const emptySubmission = () => Object.fromEntries(fields.map((field) => [field.id, ""]));
  // Saved text is remapped onto the current field list — fields added since the save start empty.
  const [submission, setSubmission] = useState<Record<string, string>>(() => initialSubmission ? restoreBuilderSubmission(initialSubmission, fields.map((field) => field.id)) : emptySubmission()); const [evaluation, setEvaluation] = useState<Evaluation | "pending">(); const [awardedXp, setAwardedXp] = useState(0); const [isReplay, setIsReplay] = useState(false); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const completedFields = fields.filter((field) => submission[field.id]?.trim()).length;
  useReportLevelPhase(evaluation ? "results" : completedFields > 0 ? "in_progress" : "fresh");
  useReportLevelDraft(() => evaluation || completedFields === 0 ? null : { mechanic: "builder", submission });
  async function submit(event: FormEvent) { event.preventDefault(); if (busy || fields.some((field) => !submission[field.id]?.trim() || submission[field.id].length > field.maxChars)) return; setError(""); setBusy(true); try { const response = await fetch("/api/builder", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ slug, submission }) }); if (!response.ok) { setError("We couldn’t evaluate your model just now. Please try again."); return; } const data = await response.json() as BuilderResponse; if (!data.evaluation) { setError("We couldn’t evaluate your model just now. Please try again."); return; } setEvaluation(data.evaluation); setAwardedXp(data.awardedXp ?? 0); setIsReplay(data.isReplay ?? false); } catch { setError("We couldn’t evaluate your model just now. Please try again."); } finally { setBusy(false); } }
  function tryAgain() { setSubmission(emptySubmission()); setEvaluation(undefined); setAwardedXp(0); setIsReplay(false); setError(""); }
  if (evaluation) return <EvaluationResults evaluation={evaluation} rubric={rubric} awardedXp={awardedXp} isReplay={isReplay} onTryAgain={tryAgain} busy={busy} error={error} nextSlug={nextSlug} successTitle="Model complete!" pendingTitle="Thanks for building your model!" />;
  return <main className="min-h-[calc(100vh-4rem)] px-4 py-8 sm:px-8"><div className="mx-auto max-w-4xl"><header className="rounded-3xl bg-[#3b2019] p-6 text-white shadow-xl shadow-[#3b2019]/15 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#f7c65a]">Builder canvas</p><h1 className="mt-2 text-3xl font-black">{title}</h1></div><div className="rounded-2xl bg-white/10 px-4 py-3 text-center"><p className="text-xl font-black">{completedFields}/{fields.length}</p><p className="text-xs font-bold uppercase tracking-wider text-[#f7e9d5]">Fields complete</p></div></div><p className="mt-4 max-w-3xl leading-7 text-[#f7e9d5]">{instructions}</p></header><form className="mt-6 space-y-5" onSubmit={submit}>{fields.map((field, index) => <section className="rounded-3xl border border-[#eadbca] bg-white p-5 shadow-sm sm:p-6" key={field.id}><div className="flex gap-3"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-[#fff0d4] text-sm font-black text-[#75420e]">{index + 1}</span><div><label className="font-black text-[#3b2019]" htmlFor={field.id}>{field.label}</label><p className="mt-1 text-sm leading-6 text-[#765343]">{field.prompt}</p></div></div><textarea className="mt-4 min-h-36 w-full rounded-2xl border border-[#ddc3aa] bg-[#fffdf9] p-4 text-[#3b2019] outline-none transition placeholder:text-[#a68a77] focus:border-[#d9873a] focus:ring-4 focus:ring-[#f9df9d]/50 disabled:bg-stone-100" id={field.id} rows={6} value={submission[field.id] ?? ""} maxLength={field.maxChars} placeholder={field.placeholder} disabled={busy} onChange={(event) => setSubmission((current) => ({ ...current, [field.id]: event.target.value }))} /><p className="mt-2 text-right text-xs font-medium text-[#876554]" aria-live="polite">{(submission[field.id] ?? "").length}/{field.maxChars} characters</p></section>)}{error ? <p className="rounded-2xl bg-rose-50 p-4 text-sm font-medium text-rose-800" role="alert">{error}</p> : null}<button className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#3b2019] px-5 py-3 text-sm font-black text-white transition hover:-translate-y-0.5 hover:bg-[#5b3024] focus:outline-none focus:ring-2 focus:ring-[#f7c65a] disabled:cursor-not-allowed disabled:opacity-50 disabled:hover:translate-y-0 sm:min-w-44" disabled={busy || completedFields !== fields.length || fields.some((field) => submission[field.id].length > field.maxChars)} type="submit">{busy ? "Evaluating your model…" : "Submit model →"}</button></form></div></main>;
}
