"use client";

import Link from "next/link";
import { useState } from "react";

type Node = { id: string; title: string; narrative: string; imageHint?: string; decisions: { id: string; label: string }[] };
type Metric = { id: string; label: string };
type Debrief = { headline: string; whatHappened: string; whyItMatters: string; realWorldNote: string; keyTerm: { term: string; definition: string } };

export default function NarrativeClient({ slug, nodes, metrics, initialNodeId, initialMetrics }: { slug: string; nodes: Node[]; metrics: Metric[]; initialNodeId: string; initialMetrics: Record<string, number> }) {
  const [nodeId, setNodeId] = useState(initialNodeId); const [values, setValues] = useState(initialMetrics); const [debrief, setDebrief] = useState<Debrief>(); const [complete, setComplete] = useState(false); const [xp, setXp] = useState(0); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const node = nodes.find((item) => item.id === nodeId);
  async function choose(decisionId: string) { setError(""); setBusy(true); try { const response = await fetch("/api/decision", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ slug, nodeId, decisionId }) }); const data = await response.json(); if (!response.ok || !data.state?.metrics) { setError("We couldn’t save that choice. Please try again."); return; } setValues(data.state.metrics); setNodeId(data.state.currentNodeId ?? nodeId); setDebrief(data.debrief); setComplete(data.completed); setXp(data.awardedXp ?? 0); } catch { setError("We couldn’t save that choice. Please try again."); } finally { setBusy(false); } }
  if (complete && !debrief) return <main className="min-h-[calc(100vh-4rem)] px-4 py-10 sm:px-8"><div className="mx-auto max-w-2xl rounded-3xl border border-emerald-200 bg-white p-8 text-center shadow-xl shadow-emerald-950/10"><p className="text-4xl">✦</p><h1 className="mt-3 text-3xl font-black text-[#3b2019]">Chapter complete</h1><p className="mt-3 text-[#765343]">You navigated the moment like a founder — decisions, trade-offs, and all.</p><p className="mx-auto mt-5 inline-flex rounded-full bg-[#fde8ad] px-4 py-2 font-black text-[#75420e]">+{xp} XP earned</p><div className="mt-6 grid grid-cols-2 gap-3">{metrics.map((metric) => <div className="rounded-2xl bg-[#fff7ea] p-3" key={metric.id}><p className="text-xs font-bold uppercase tracking-wider text-[#a65e2e]">{metric.label}</p><p className="mt-1 text-xl font-black text-[#3b2019]">{values[metric.id]}</p></div>)}</div><Link className="mt-7 inline-flex rounded-xl bg-[#3b2019] px-5 py-3 font-bold text-white" href="/">Back to map</Link></div></main>;
  if (debrief) return <main className="min-h-[calc(100vh-4rem)] px-4 py-8 sm:px-8"><div className="mx-auto max-w-3xl rounded-3xl border border-[#eadbca] bg-white p-6 shadow-xl shadow-[#6c4127]/10 sm:p-9"><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#a65e2e]">Founder debrief</p><h1 className="mt-2 text-3xl font-black text-[#3b2019]">{debrief.headline}</h1><div className="mt-6 space-y-5 text-[#604536]"><p className="leading-7">{debrief.whatHappened}</p><section className="rounded-2xl bg-[#fff3d7] p-5"><h2 className="font-black text-[#75420e]">Why it matters</h2><p className="mt-2 leading-7">{debrief.whyItMatters}</p></section><p className="leading-7">{debrief.realWorldNote}</p><section className="rounded-2xl border border-[#b9ded1] bg-[#f0fbf6] p-5"><p className="text-xs font-bold uppercase tracking-wider text-[#2f7960]">Key term</p><h2 className="mt-1 text-lg font-black text-[#245b48]">{debrief.keyTerm.term}</h2><p className="mt-2 leading-6 text-[#245b48]">{debrief.keyTerm.definition}</p></section></div><button className="mt-7 rounded-xl bg-[#3b2019] px-5 py-3 font-bold text-white" onClick={() => setDebrief(undefined)}>Continue the story →</button></div></main>;
  if (!node) return null;
  return <main className="min-h-[calc(100vh-4rem)] px-4 py-8 sm:px-8"><div className="mx-auto max-w-4xl"><div className="rounded-3xl bg-[#3b2019] p-6 text-white shadow-xl shadow-[#3b2019]/15 sm:p-8"><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#f7c65a]">Founder story</p><h1 className="mt-2 text-3xl font-black">{node.title}</h1><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{metrics.map((metric) => <div className="rounded-2xl bg-white/10 p-3" key={metric.id}><p className="text-xs font-bold uppercase tracking-wider text-[#f7e9d5]">{metric.label}</p><p className="mt-1 text-xl font-black">{values[metric.id]}</p></div>)}</div></div><section className="mt-6 rounded-3xl border border-[#eadbca] bg-white p-6 shadow-sm sm:p-8">{node.imageHint ? <p className="inline-flex rounded-full bg-[#f7eee1] px-3 py-1 text-xs font-bold text-[#765343]">Scene: {node.imageHint}</p> : null}<p className="mt-5 max-w-3xl text-lg leading-8 text-[#4b3024]">{node.narrative}</p>{error ? <p className="mt-5 rounded-xl bg-rose-50 p-3 text-sm font-medium text-rose-800">{error}</p> : null}<div className="mt-7 grid gap-3">{node.decisions.map((decision) => <button className="rounded-2xl border border-[#e4c9a9] bg-[#fffaf4] p-4 text-left font-bold text-[#3b2019] transition hover:-translate-y-0.5 hover:border-[#d9873a] hover:bg-[#fff1d8] disabled:cursor-wait disabled:opacity-60" disabled={busy} key={decision.id} onClick={() => choose(decision.id)}>{decision.label}<span className="ml-2 text-[#a65e2e]">→</span></button>)}</div></section></div></main>;
}
