import { notFound } from "next/navigation";
import { getLevelBySlug, loadAllLevels } from "../../../lib/game/content";
import { shuffleSteps } from "../../../lib/game/scoring";
import PlayClient from "./play-client";
import NarrativeClient from "./narrative-client";
import RoleplayClient from "./roleplay-client";
import BuilderClient from "./builder-client";
import LevelHeader from "./level-header";
export default async function PlayPage({params}:{params:Promise<{slug:string}>}) { const {slug}=await params; const level=getLevelBySlug(slug); if(!level) notFound(); const levels=loadAllLevels(); const nextSlug=levels[levels.findIndex((item)=>item.slug===slug)+1]?.slug; const header=<LevelHeader title={level.title}/>; if(level.gameplay.kind==="narrative") return <>{header}<NarrativeClient slug={slug} nodes={level.gameplay.nodes} metrics={level.gameplay.metrics} initialNodeId={level.gameplay.startNodeId} initialMetrics={Object.fromEntries(level.gameplay.metrics.map(m=>[m.id,m.start]))}/></>; if(level.gameplay.kind==="sort_buckets") return <>{header}<PlayClient slug={slug} kind="sort_buckets" scenario={level.gameplay.scenario} items={level.gameplay.items} buckets={level.gameplay.buckets}/></>; if(level.gameplay.kind==="sequence") return <>{header}<PlayClient slug={slug} kind="sequence" scenario={level.gameplay.scenario} steps={shuffleSteps(level.gameplay.steps, 42)}/></>; if(level.gameplay.kind==="roleplay") return <>{header}<RoleplayClient slug={slug} title={level.title} setup={level.gameplay.setup} persona={level.gameplay.persona} rubric={level.gameplay.rubric} nextSlug={nextSlug} /></>; if(level.gameplay.kind==="builder") return <>{header}<BuilderClient slug={slug} title={level.title} instructions={level.gameplay.instructions} fields={level.gameplay.fields} rubric={level.gameplay.rubric} nextSlug={nextSlug} /></>; notFound(); }
