"use client";

import { FormEvent, useState } from "react";
import EvaluationResults, { type Criterion, type Evaluation } from "./evaluation-results";

type Persona = { name: string; role: string; maxTurns: number };
type Message = { role: "player" | "persona"; content: string };
type TurnResponse = { personaTurn?: { message: string }; turnNumber: number; maxTurns: number; messages?: Message[]; evaluation?: Evaluation | "pending"; awardedXp?: number };

export default function RoleplayClient({ slug, title, setup, persona, rubric }: { slug: string; title: string; setup: string; persona: Persona; rubric: Criterion[] }) {
  const [messages, setMessages] = useState<Message[]>([]); const [input, setInput] = useState(""); const [turnNumber, setTurnNumber] = useState(0); const [maxTurns, setMaxTurns] = useState(persona.maxTurns); const [evaluation, setEvaluation] = useState<Evaluation | "pending">(); const [awardedXp, setAwardedXp] = useState(0); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function request(body: Record<string, string>): Promise<TurnResponse | null> { setError(""); setBusy(true); try { const response = await fetch("/api/roleplay", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (!response.ok) { setError(`We couldn’t reach ${persona.name} just now. Please try again.`); return null; } return await response.json() as TurnResponse; } catch { setError(`We couldn’t reach ${persona.name} just now. Please try again.`); return null; } finally { setBusy(false); } }
  async function submit(event: FormEvent) { event.preventDefault(); if (!input.trim() || input.length > 800 || busy) return; const playerMessage = input.trim(); const data = await request({ slug, message: playerMessage }); if (!data) return; setInput(""); setMessages((current) => [...current, { role: "player", content: playerMessage }, ...(data.personaTurn ? [{ role: "persona" as const, content: data.personaTurn.message }] : [])]); setTurnNumber(data.turnNumber); setMaxTurns(data.maxTurns); if (data.evaluation) setEvaluation(data.evaluation); setAwardedXp(data.awardedXp ?? 0); }
  async function restart() { const data = await request({ slug, action: "restart" }); if (!data) return; setMessages(data.messages ?? []); setTurnNumber(data.turnNumber); setMaxTurns(data.maxTurns); setInput(""); setEvaluation(undefined); setAwardedXp(0); }
  if (evaluation) return <EvaluationResults evaluation={evaluation} rubric={rubric} awardedXp={awardedXp} onTryAgain={restart} busy={busy} error={error} />;
  return <main className="min-h-screen px-4 py-8 sm:px-8"><div className="mx-auto max-w-3xl"><header className="rounded-3xl bg-[#3b2019] p-6 text-white shadow-xl shadow-[#3b2019]/15 sm:p-8"><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#f7c65a]">Live roleplay</p><h1 className="mt-2 text-3xl font-black">{title}</h1><p className="mt-3 max-w-2xl leading-7 text-[#f7e9d5]">{setup}</p><div className="mt-5 flex items-center justify-between rounded-2xl bg-white/10 px-4 py-3 text-sm"><span>Speaking with <b>{persona.name}</b> · {persona.role}</span><span className="rounded-full bg-[#f7c65a] px-2.5 py-1 font-black text-[#3b2019]">Turn {turnNumber}/{maxTurns}</span></div></header><section className="mt-6 rounded-3xl border border-[#eadbca] bg-white p-5 shadow-sm sm:p-7"><div className="min-h-48 space-y-4">{messages.length === 0 ? <div className="grid min-h-48 place-items-center rounded-2xl border border-dashed border-[#ddc3aa] bg-[#fffaf4] p-6 text-center"><p className="max-w-sm text-[#765343]">Your opening line sets the tone. Be clear about the idea, the customer, and why it matters.</p></div> : messages.map((message, index) => <div className={`max-w-[88%] rounded-2xl p-4 ${message.role === "player" ? "ml-auto bg-[#fff0d4] text-[#4b3024]" : "bg-[#eff9f4] text-[#245b48]"}`} key={`${message.role}-${index}`}><p className="text-xs font-black uppercase tracking-wider opacity-70">{message.role === "player" ? "You" : persona.name}</p><p className="mt-1 leading-6">{message.content}</p></div>)}</div><form className="mt-6 border-t border-[#f1e7dc] pt-6" onSubmit={submit}><label className="font-black text-[#3b2019]" htmlFor="roleplay-message">Your response</label><textarea className="mt-3 min-h-32 w-full rounded-2xl border border-[#ddc3aa] bg-[#fffdf9] p-4 text-[#3b2019] outline-none transition placeholder:text-[#a68a77] focus:border-[#d9873a] focus:ring-4 focus:ring-[#f9df9d]/50 disabled:bg-stone-100" id="roleplay-message" value={input} maxLength={801} rows={5} disabled={busy} placeholder="Write what you would say…" onChange={(event) => setInput(event.target.value)} /><div className="mt-2 flex items-center justify-between gap-3 text-xs text-[#876554]"><span>{input.length}/800 characters</span>{input.length > 800 ? <span className="font-bold text-rose-700">Keep it to 800 characters or fewer.</span> : null}</div>{error ? <p className="mt-3 rounded-xl bg-rose-50 p-3 text-sm font-medium text-rose-800">{error}</p> : null}<button className="mt-5 rounded-xl bg-[#3b2019] px-5 py-3 font-bold text-white transition hover:bg-[#5b3024] disabled:cursor-not-allowed disabled:opacity-50" disabled={busy || !input.trim() || input.length > 800} type="submit">{busy ? "Sending…" : "Send response →"}</button></form></section></div></main>;
}
