"use client";

import { FormEvent, useState } from "react";
import EvaluationResults, { type Criterion, type Evaluation } from "./evaluation-results";

type Persona = { name: string; role: string; maxTurns: number };
type Message = { role: "player" | "persona"; content: string };
type TurnResponse = { personaTurn?: { message: string }; turnNumber: number; maxTurns: number; messages?: Message[]; evaluation?: Evaluation | "pending"; awardedXp?: number };

export default function RoleplayClient({ slug, title, setup, persona, rubric }: { slug: string; title: string; setup: string; persona: Persona; rubric: Criterion[] }) {
  const [messages, setMessages] = useState<Message[]>([]); const [input, setInput] = useState(""); const [turnNumber, setTurnNumber] = useState(0); const [maxTurns, setMaxTurns] = useState(persona.maxTurns); const [evaluation, setEvaluation] = useState<Evaluation | "pending">(); const [awardedXp, setAwardedXp] = useState(0); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function request(body: Record<string, string>): Promise<TurnResponse | null> { setError(""); setBusy(true); try { const response = await fetch("/api/roleplay", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (!response.ok) { setError("We couldn’t reach Meera just now. Please try again."); return null; } return await response.json() as TurnResponse; } catch { setError("We couldn’t reach Meera just now. Please try again."); return null; } finally { setBusy(false); } }
  async function submit(event: FormEvent) { event.preventDefault(); if (!input.trim() || input.length > 800 || busy) return; const playerMessage = input.trim(); const data = await request({ slug, message: playerMessage }); if (!data) return; setInput(""); setMessages((current) => [...current, { role: "player", content: playerMessage }, ...(data.personaTurn ? [{ role: "persona" as const, content: data.personaTurn.message }] : [])]); setTurnNumber(data.turnNumber); setMaxTurns(data.maxTurns); if (data.evaluation) setEvaluation(data.evaluation); setAwardedXp(data.awardedXp ?? 0); }
  async function restart() { const data = await request({ slug, action: "restart" }); if (!data) return; setMessages(data.messages ?? []); setTurnNumber(data.turnNumber); setMaxTurns(data.maxTurns); setInput(""); setEvaluation(undefined); setAwardedXp(0); }
  if (evaluation) return <EvaluationResults evaluation={evaluation} rubric={rubric} awardedXp={awardedXp} onTryAgain={restart} busy={busy} error={error} />;
  return <main className="min-h-screen p-6"><h1 className="text-2xl font-bold">{title}</h1><p className="mt-3 max-w-2xl">{setup}</p><p className="mt-4 text-sm">Speaking with {persona.name} · Turn {turnNumber} of {maxTurns}</p><div className="mt-5 max-w-2xl space-y-3">{messages.map((message, index) => <div className={`border p-3 ${message.role === "player" ? "bg-yellow-50" : "bg-slate-50"}`} key={`${message.role}-${index}`}><b>{message.role === "player" ? "You" : persona.name}</b><p>{message.content}</p></div>)}</div><form className="mt-5 max-w-2xl" onSubmit={submit}><label className="block font-semibold" htmlFor="roleplay-message">Your pitch</label><textarea className="mt-2 w-full border p-3" id="roleplay-message" value={input} maxLength={801} rows={5} disabled={busy} onChange={(event) => setInput(event.target.value)} />{input.length > 800 && <p className="mt-1 text-sm text-red-700">Please keep your message to 800 characters or fewer.</p>}{error && <p className="mt-2 text-red-700">{error}</p>}<button className="mt-3 border bg-black px-4 py-2 text-white" disabled={busy || !input.trim() || input.length > 800} type="submit">{busy ? "Sending…" : "Send pitch"}</button></form></main>;
}
